### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by dmke** [digineo/dnsgit#1]
In `lib/zone.rb` are multiple references to class `Fixnum` (when comparing arguments). Since Ruby 2.4, the distinction between `Fixnum` and `Bignum` is considered an implementation detail of the interpreter. At least MRI 2.5 issues a warning when using `Fixnum` (haven't tested against Ruby 2.4):

```
remote: .../lib/zone.rb:195: warning: constant ::Fixnum is deprecated
remote: .../lib/zone.rb:156: warning: constant ::Fixnum is deprecated
remote: .../lib/zone.rb:157: warning: constant ::Fixnum is deprecated
remote: .../lib/zone.rb:158: warning: constant ::Fixnum is deprecated
```

*N.B. this is not a bug, only annoying :-)*

**Comment by corny** [comment]
Thanks a lot!
